<?php 

define("db_name","%db_name%");				// the name of the database
define("db_host","%db_host%");				// the name or IP address of the host computer
define("db_user","%db_user%");				// user name for this database
define("db_pw","%db_pass%");					// password for this database 

define("la_adjustment", 60*35);				// subtract 30 minutes for lunch and 5 minutes for getting in and out

define('la_admin_email','%admin_email%');
define('la_from_email','%from_email%');

define ("debugging_on",0);
define ("is_demo",0);

?>
