<?php 

define("db_name","latrixdemo");				// the name of the database
define("db_host","127.0.0.1");				// the name or IP address of the host computer
define("db_user","latrix");					// user name for this database
define("db_pw","latrix");						// password for this database 
define("is_demo", 1);

define("la_adjustment", 60*35);				// subtract 30 minutes for lunch and 5 minutes for getting in and out

define('la_admin_email','wolfgangs@manticoreit.com');
define('la_from_email','admin@latrix.co.uk');
define ("debugging_on",0);

?>
