<?php 

define("db_name","latrax");                                     // the name of the database
define("db_host","localhost");                          // the name or IP address of the host computer
define("db_user","latimer");                                    // user name for this database
define("db_pw","gotcha");                                               // pasword for this database 

define("is_demo", 0);
define ("debugging_on",1);

define("la_adjustment", 60*35);                         // subtract 30 minutes for lunch and 5 minutes for getting in and out

define('la_admin_email','wolfgangs@manticoreit.com');
define('la_from_email','admin@latrix.co.uk');
?>
