CREATE TABLE [SchoolRegForm]

ALTER TABLE dbo.[Temp Enquiry] ADD
  [SessionId] varchar(100) NULL

ALTER TABLE dbo.[Temp Enquiry] ADD
  [Physically Remarks] varchar(80) NULL
  [MotherDOB] varchar(11) NULL
  [FatherDOB] varchar(80) NULL
  [MotherDesignation] varchar(80) NULL,
  [FatherDesignation] varchar(80) NULL,
  [MotherOrganization] varchar(80) NULL,
  [FatherOrganization] varchar(80) NULL
  [MaritalStatus] varchar(2) NULL,
  [ChildName1] varchar(100) NULL,
  [ChildName2] varchar(100) NULL,
  [ChildName3] varchar(100) NULL,
  [ChildName4] varchar(100) NULL,
  [ChildAge1] varchar(2) DEFAULT NULL,
  [ChildAge2] varchar(2) DEFAULT NULL,
  [ChildAge3] varchar(2) DEFAULT NULL,
  [ChildAge4] varchar(2) DEFAULT NULL,
  [ChildGender1] varchar(2) DEFAULT NULL,
  [ChildGender2] varchar(2) DEFAULT NULL,
  [ChildGender3] varchar(2) DEFAULT NULL,
  [ChildGender4] varchar(2) DEFAULT NULL,
  [ChildClass1] varchar(15) NULL,
  [ChildClass2] varchar(15) NULL,
  [ChildClass3] varchar(15) NULL,
  [ChildClass4] varchar(15) NULL,
  [ChildSchool1] varchar(45) NULL,
  [ChildSchool2] varchar(45) NULL,
  [ChildSchool3] varchar(45) NULL,
  [ChildSchool4] varchar(45) NULL
  [Sibling] varchar(2) DEFAULT NULL,
  [Staff] varchar(2) DEFAULT NULL,
  [MotherTongue] varchar(45) NULL,
  [Caste] varchar(45) NULL,
  [TransportMode] varchar(45) NULL,
  [USN1] varchar(45) NULL,
  [USN2] varchar(45) NULL,
  [USN3] varchar(45) NULL,
  [USN4] varchar(45) NULL,
  [Picture] varchar(200) NULL
  
 
 
  

select * from [Temp Enquiry]

CREATE TABLE dbo.SchoolRegistrationForm
   ([ID] int PRIMARY KEY NOT NULL IDENTITY(1,1),
   [SchoolID] varchar(11) NOT NULL,
  [AcadYear] varchar(8) NULL,
  [RegNo] varchar(15) NULL,
  [Candidate] varchar(80) NULL,
  [Sex] varchar(2) NULL,
  [Nationality] varchar(20) NULL,
  [DOB] varchar(11) NULL,
  [Age] varchar(11) NULL,
  [ClassApplied] varchar(15) NULL,
  [LastSchool] varchar(100) NULL,
  [MotherName] varchar(80) NULL,
  [FatherName] varchar(80) NULL,
  [MotherDOB] varchar(11) NULL,
  [FatherDOB] varchar(11) NULL,
  [MotherEducation] varchar(80) NULL,
  [FatherEducation] varchar(80) NULL,
  [MotherMobile] varchar(15) NULL,
  [FatherMobile] varchar(15) NULL,
  [MotherOccupation] varchar(80) NULL,
  [FatherOccupation] varchar(80) NULL,
  [MotherDesignation] varchar(80) NULL,
  [FatherDesignation] varchar(80) NULL,
  [MotherOrganization] varchar(80) NULL,
  [FatherOrganization] varchar(80) NULL,
  [MotherOfficeAddress] varchar(100) NULL,
  [FatherOfficeAddress] varchar(100) NULL,
  [ResidentialAddress] varchar(100) NULL,
  [ResidentialPhone] varchar(15) NULL,
  [EmergencyNo] varchar(15) NULL,
  [Email] varchar(100) NULL,
  [MaritalStatus] varchar(2) NULL,
  [ChildName1] varchar(100) NULL,
  [ChildName2] varchar(100) NULL,
  [ChildName3] varchar(100) NULL,
  [ChildName4] varchar(100) NULL,
  [ChildAge1] varchar(2) DEFAULT NULL,
  [ChildAge2] varchar(2) DEFAULT NULL,
  [ChildAge3] varchar(2) DEFAULT NULL,
  [ChildAge4] varchar(2) DEFAULT NULL,
  [ChildGender1] varchar(2) DEFAULT NULL,
  [ChildGender2] varchar(2) DEFAULT NULL,
  [ChildGender3] varchar(2) DEFAULT NULL,
  [ChildGender4] varchar(2) DEFAULT NULL,
  [ChildClass1] varchar(15) NULL,
  [ChildClass2] varchar(15) NULL,
  [ChildClass3] varchar(15) NULL,
  [ChildClass4] varchar(15) NULL,
  [ChildSchool1] varchar(45) NULL,
  [ChildSchool2] varchar(45) NULL,
  [ChildSchool3] varchar(45) NULL,
  [ChildSchool4] varchar(45) NULL,
  [AppDate] varchar(20) NULL,
  [Sibling] varchar(2) DEFAULT NULL,
  [Staff] varchar(2) DEFAULT NULL,
  [PIN] varchar(6) NULL,
  [State] varchar(45) NULL,
  [City] varchar(45) NULL,
  [RcvdStatus] varchar(1) NULL,
  [RcvdDate] varchar(15) NULL,
  [MotherEmail] varchar(80) NULL,
  [FatherEmail] varchar(80) NULL,
  [MotherTongue] varchar(45) NULL,
  [Religion] varchar(45) NULL,
  [Caste] varchar(45) NULL,
  [MotherIncome] varchar(20) NULL,
  [FatherIncome] varchar(20) NULL,
  [Distance] varchar(5) NULL,
  [TransportMode] varchar(45) NULL,
  [USN1] varchar(45) NULL,
  [USN2] varchar(45) NULL,
  [USN3] varchar(45) NULL,
  [USN4] varchar(45) NULL,
  [PhysicallyChallenged] varchar(4) NULL,
  [PhysicallyRemarks] varchar(45) NULL,
  [SubmissionDate] varchar(20) NULL,
  [InterviewDate] varchar(20) NULL,
  [EmlSubmissionDate] varchar(20) NULL,
  [EmlInterviewDate] varchar(20) NULL,
  [Invalid] varchar(4) NULL,
  [PrevClass] varchar(15) NULL,
  [Language1] varchar(45) NULL,
  [Language2] varchar(45) NULL,
  [MediumOfInstruction] varchar(45) NULL,
  [Orientation] varchar(4) NULL,
  [OrientationDate] varchar(20) NULL,
  [Picture] varchar(100) NULL )
  GO
DROP TABLE SchoolRegistrationForm;
select * from SchoolRegistrationForm

