<?php
	require_once("SetupLeft.php");
?>
<?php

	//Upload file
	if(basename($_FILES["fileToUpload"]["name"])){
	require_once("FileToUpload.php");
	}
	//Validate School Entry
                $SQL = "INSERT INTO [Company Information] (
				[Abbreviated Name],
				[Address],
				[Address 2],
				[Adress3],
				[Assessing Officer],
				[Bank Account No_],
				[Bank Branch No_],
				[Bank Name],
				[Base Calendar Code],
				[Brand],
				[C_E_ Commissionerate],
				[C_E_ Division],
				[C_E_ Range],
				[C_E_ Registration No_],
				[C_S_T No_],
				[Cal_ Convergence Time Frame],
				[Cash Account No_],
				[Central STC Applicable],
				[Check-Avail_ Period Calc_],
				[Check-Avail_ Time Bucket],
				[Circle No_],
				[City],
				[Company Code],
				[Company Name],
				[Company Registration  No_],
				[Company Status],
				[Company Status1],
				[Company Type],
				[Composition],
				[Composition Type],
				[Country_Region Code],
				[County],
				[Customs Permit Date],
				[Customs Permit No_],
				[DDO Code],
				[DDO Registration No_],
				[Deductor Category],
				[E_C_C_ No_],
				[E-Mail],
				[Export or Deemed Export],
				[Factories Act_ Regd_ No_],
				[Fax No_],
				[Giro No_],
				[Home Page],
				[IBAN],
				[IC Inbox Details],
				[IC Inbox Type],
				[IC Partner Code],
				[Industrial Classification],
				[Input Service Distributor],
				[InsertStatus],
				[L_S_T_ No_],
				[Large Tax Payer],
				[Large Tax Payer City],
				[Location Code],
				[Manufacturers Code],
				[Ministry Code],
				[Ministry Type],
				[Name],
				[Name 2],
				[P_A_N_ No_],
				[P_A_N_ Status],
				[PAO Code],
				[PAO Registration No_],
				[Payment Routing No_],
				[Phone No_],
				[Phone No_ 2],
				[Picture],
				[Post Code],
				[Primary Key],
				[RAccount Name],
				[RAccount No_],
				[RBank Name],
				[RBranch Address],
				[Registration No_],
				[Responsibility Center],
				[RIFSC Code],
				[School Name],
				[School Type],
				[Service Tax Registration No_],
				[Ship-to Address],
				[Ship-to Address 2],
				[Ship-to City],
				[Ship-to Contact],
				[Ship-to Country_Region Code],
				[Ship-to County],
				[Ship-to Name],
				[Ship-to Name 2],
				[Ship-to Post Code],
				[Show Abbreviated Name],
				[ST Payment Due Day],
				[ST Payment Period],
				[State],
				[SWIFT Code],
				[Synchronization],
				[T_A_N_ No_],
				[T_C_A_N_ No_],
				[T_I_N_ No_],
				[Telex Answer Back],
				[Telex No_],
				[Trading Co_],
				[Trust],
				[UpdateStatus],
				[VAT Registration No_],
				[Ward No_]

			) VALUES (				
								'',
				'".substr($_REQUEST['Address1'],0, 50)."',
				'".substr($_REQUEST['Address2'],0, 50)."',
				'".substr($_REQUEST['Address3'],0, 250)."',
				'".substr($_REQUEST['AssessingOfficer'],0, 30)."',
				'',
				'',
				'',
				'',
				".($_REQUEST['Brand']<>""? $_REQUEST['Brand']:0).",
				'',
				'',
				'',
				'',
				'".substr($_REQUEST['CSTNo'],0, 20)."',
				'',
				'',
				".($_REQUEST['CentralSTC']<>""?$_REQUEST['CentralSTC']:0).",
				'',
				0,
				'".substr($_REQUEST['CircleNo'],0, 30)."',
				'".substr($_REQUEST['City'],0, 30)."',
				'',
				'".substr($_REQUEST['Name'],0, 400)."',
				'',
				".($_REQUEST['CentralSTC']<>""?$_REQUEST['CentralSTC']:0).",
				0,
				0,
				".($_REQUEST['Composition']<>""?$_REQUEST['Composition']:0).",
				".($_REQUEST['CompositionType']<>""?$_REQUEST['CompositionType']:0).",
				'".substr($_REQUEST['CountryCode'],0, 10)."',
				'".substr($_REQUEST['CountryCode'],0, 30)."',
				'1900-01-01',
				'',
				'".substr($_REQUEST['DDOCode'],0, 20)."',
				'".substr($_REQUEST['DDORegistrationNo'],0, 10)."',
				'".substr($_REQUEST['DeductorCategory'],0, 1)."',
				'',
				'".substr($_REQUEST['Email'],0, 80)."',
				".($_REQUEST['ExportorDeemed']<>""?$_REQUEST['ExportorDeemed']:0).",
				'',
				'".substr($_REQUEST['FaxNo'],0, 30)."',
				'',
				'".substr($_REQUEST['HomePage'],0, 80)."',
				'',
				'".substr($_REQUEST['ICInboxDetails'],0, 250)."',
				".($_REQUEST['ICInboxType']<>""?$_REQUEST['ICInboxType']:0).",
				'".substr($_REQUEST['ICPartnerCode'],0, 20)."',
				'',
				".($_REQUEST['InputService']<>""?$_REQUEST['InputService']:0).",
				0,
				'".substr($_REQUEST['LSTNo'],0, 20)."',
				0,
				'',
				'',
				'',
				'".substr($_REQUEST['MinistryCode'],0, 3)."',
				".($_REQUEST['MinistryType']<>""?$_REQUEST['MinistryType']:0).",
				'".substr($_REQUEST['Name'],0, 50)."',
				'".substr($_REQUEST['SchoolName2'],0, 100)."',
				'".substr($_REQUEST['PANNo'],0, 20)."',
				".($_REQUEST['PANStatus']<>""?$_REQUEST['PANStatus']:0).",
				'".substr($_REQUEST['PAOCode'],0, 20)."',
				'".substr($_REQUEST['PAORegistrationNo'],0, 7)."',
				'',
				'".substr($_REQUEST['PhoneNo'],0, 30)."',
				'".substr($_REQUEST['PhoneNo2'],0, 30)."',
				'".$target_file."',
				'".substr($_REQUEST['PostCode'],0, 20)."',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'".substr($_REQUEST['SchoolName'],0, 50)."',
				".($_REQUEST['SchoolType']<>""?$_REQUEST['SchoolType']:0).",
				'".substr($_REQUEST['ServiceTaxRegistration'],0, 20)."',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				0,
				".($_REQUEST['STPaymentDueDate']<>""?$_REQUEST['STPaymentDueDate']:0).",
				".($_REQUEST['STPaymentPeriod']<>""?$_REQUEST['STPaymentPeriod']:0).",
				'".substr($_REQUEST['State'],0, 10)."',
				'',
				0,
				'".substr($_REQUEST['TANNo'],0, 10)."',
				'".substr($_REQUEST['TCANNo'],0, 10)."',
				'".substr($_REQUEST['TINNo'],0, 11)."',
				'',
				'',
				0,
				'".substr($_REQUEST['Trust'],0, 100)."',
				0,
				'".substr($_REQUEST['VATRegistration'],0, 20)."',
				'".substr($_REQUEST['WardNo'],0, 30)."'
			)";
                //exit($SQL);
                $result = odbc_exec($conn, $SQL) or die(odbc_errormsg($conn));
                if(!result){
                    exit("<div class='alert alert-danger alert-error'><strong>Error!</strong> There is some problem, please check.</div>");
                }
		else{
			
			//Success Message
			echo "<div class='alert alert-success alert-error'><strong>Success!</strong> Company has been registered.</div>";
		}
		
		
		/*
		
		if($result){
			echo "<div class='container'><div class='alert alert-success alert-error'><strong>Success!</strong> Company has been registered.</div></div>";
		}
		else{
			echo "<div class='container'><div class='alert alert-danger alert-error'><strong>Error!</strong> There is some problem, please check.</div></div>";
		}
	}
	else{
		echo "<div class='container'><div class='alert alert-danger alert-error'><strong>Error!</strong> This company is already registered.</div></div>";
	}
                 
                 */
	require_once("SetupRight.php");
?>